### ISSUE TITLE
即刻RSS

### ISSUE THREAD

**Issue by LuzMasonj** [idealclover/Easy-to-RSS#2]
如何订阅即刻的RSS 通过网页版不行啊
![image](https://user-images.githubusercontent.com/27768847/45260978-5c001180-b428-11e8-869b-68b0e9aa890b.png)

**Comment by idealclover** [comment]
即刻的RSS现在还没有添加到大版本中，过两天会release

**Comment by LuzMasonj** [comment]
rsshub中的类似这样的rss https://rsshub.app/jike/topic/58aaf4fb4dfce8001505d669
这是临时的还是永久的地址

**Comment by idealclover** [comment]
永久的 这是即刻主题的id

**Comment by LuzMasonj** [comment]
![screenshot_2018-09-09-20-45-21](https://user-images.githubusercontent.com/27768847/45264577-7f18ca00-b404-11e8-8889-28c28b4b1aa4.png)
图上rsshub的说明文档中的开头部分 说这是演示地址 缓存10分钟 不是只能用10分钟的意思吗

**Comment by idealclover** [comment]
不是 缓存十分钟的意思是刷新时间为十分钟，最坏情况下可能原即刻源更新十分钟后
RSS才会有更新

**Comment by LuzMasonj** [comment]
多谢老哥 明白了 看说明文档上说是要在自己的vps上搭建rss 即然演示的能正常使用 为什么还要我们自己搭呢

**Comment by idealclover** [comment]
首先，从经济角度讲，在自己vps上搭建rss不是一件难事，而且比如知乎等可能有反爬虫政策，自己搭建可以使得消息更加及时，被封的可能性大大降低
其次，从道义上说，作为一个开源网站，这个示例RSS的服务器是DIYgod自费的，从道理上讲我们也不应当过度使用。之前的一些国内外开源项目中，开发者无法负担服务器费用也是项目延续的一大原因。虽然我们享受到了便利，但从另一个角度讲，也不应当给开发者过重的负担。

**Comment by LuzMasonj** [comment]
![screenshot_20180910-171625](https://user-images.githubusercontent.com/27768847/45288515-7a115480-b4b0-11e8-849a-e960ad644dd1.jpg)
老哥  为什么有个别即刻rss点开提示这个
![image](https://user-images.githubusercontent.com/27768847/45288724-f4c48900-b51d-11e8-84fe-4fbc7898ee3a.png)
电脑打开提示消息不存在
![screenshot_20180910-172227](https://user-images.githubusercontent.com/27768847/45289838-bd20f700-b4b3-11e8-96d3-e79e2319b695.jpg)
即刻中正常
![screenshot_20180910-172232](https://user-images.githubusercontent.com/27768847/45289851-c3af6e80-b4b3-11e8-9037-64aa4d1ddbcb.jpg)
点开外链是公众号
地址为https://github.com/idealclover/Easy-to-RSS/issues/2#issuecomment-419845726

**Comment by idealclover** [comment]
本repo的对即刻相关支持问题已解决，上面的看起来是RSSHub的bug
