### ISSUE TITLE
[功能请求] 希望能支持 Firefox

### ISSUE THREAD

**Issue by fang5566** [idealclover/Easy-to-RSS#4]
这个扩展在 Chrome 上面十分顺手，不知道是否有计划支持 Firefox。Firefox 和 Chrome 的扩展使用相似的架构，移植难度降低很多。

**Comment by maxox** [comment]
+1

**Comment by idealclover** [comment]
收到ww最近有点忙 有时间会做~

**Comment by idealclover** [comment]
Done. （事实上根本不需要改代码2333
