### ISSUE TITLE
地址错误

### ISSUE THREAD

**Issue by YeomanYe** [idealclover/Easy-to-RSS#5]
打开options不设置任何地址保存后，再使用origin就变成了插件的

**Comment by idealclover** [comment]
唔可以提供一下具体的使用场景吗？蟹蟹！
例如：网站URL，是chrome还是firefox~包括操作流程~

**Comment by YeomanYe** [comment]
使用的是chrome浏览器，将easy-to-rss的地址留空保存之后，对github issues生成rss时地址错误。

生成的地址会变成扩展的地址：

`chrome-extension://hbcmpkcpbnecinpngdnfbnknfkdpdfli/github/issue/idealclover/Easy-to-RSS`

原生成地址：

`https://rsshub.app/github/issue/idealclover/Easy-to-RSS`

**Comment by idealclover** [comment]
成功复现bug，暂时可通过卸载并重新安装解决

**Comment by YeomanYe** [comment]
> 成功复现bug，暂时可通过卸载并重新安装解决

哈哈哈，好巧啊，我也是这么想的

**Comment by idealclover** [comment]
容易修的，下个版本就着手解决ww

**Comment by YeomanYe** [comment]
@idealclover 好的，最近太忙了要不然就自己上了

**Comment by iamdalaba** [comment]
[https://www.chromefor.com/easy-to-rss_v0-2-0/](https://www.chromefor.com/easy-to-rss_v0-2-0/) 
国内可以下载，多个节点
