### ISSUE TITLE
修改地址无效

### ISSUE THREAD

**Issue by YeomanYe** [idealclover/Easy-to-RSS#6]
多次修改rsshub服务器地址后，插件使用的地址始终为默认地址：`https://rsshub.app/`

**Comment by idealclover** [comment]
唔~ 可以说一下是用chrome还是firefox吗~ 具体的版本呢~ 蟹蟹！

**Comment by YeomanYe** [comment]
chrome最新版，插件是网上商店下载的0.1.0版本
